### ISSUE TITLE
Log In Screen to Profile

### ISSUE THREAD

**Issue by ESmit147** [COSC481W-2022Winter/capstone-wicrosoft#2]
Acceptance criteria:
if the user fills in the correct username and password, then click the sign-in button, the user should be logged in and view the profile page, which has the full name and the role of the user, and a log out.

if the user fills in the incorrect username and password, the user should not be logged in, and the user should see a warning.

if the username or the password is left blank when the sign-in button is clicked, the user should see a warning.

the sign-in process and the password storage follows a standard to protect users' private information.

when the user click log out on the profile page, the user will be redirected to the sign in page.

after the user log out, the user cannot access the profile page using the URL

Tasks:
1. fill the database with the test data (Austin Ahlijian)
2. Login: (Keegan/Elijah)
    2.1 html
    2.2 django view
    2.3 form
    2.3.1 pass all the information to backend
    2.3.1 show warnings when the login is not successful or the username/password is blank
    2.4. backend: query the database to check the credentials

3.Profile: (Keegan/Elijah)
    3.1 html
    3.2 django view
    3.3 query and get the full name and the role
    3.4. backend: query the database to retrieve full name and the role

**Comment by bsimmo11** [comment]
Issue was resolved and merged with main.
