### ISSUE TITLE
Feat: Creation of Team Page to display a given team

### ISSUE THREAD

**Issue by ESmit147** [COSC481W-2022Winter/capstone-wicrosoft#26]
As a user, I would like the ability to look at other public company team. Seeing information revolving around their members, projects, and their goals as a team.

Constraints:
1. Team must be within the database
2. Have page that shows specific team
3. url takes team_id parameter and displays team info
4. Team must be of type "public" to be viewed by non-managers.

Acceptance Criteria:
If an authorized profile access a Team page:
- should be able to view members, projects, and goals
- if team is set to private, cannot be viewed except by members or manager
- Filter users and only allow access to team creation page to manager users

If an unauthorized user accesses a Team page or if a private team page is accessed by non-team members:
- redirect to log in or home page if already logged in

Tasks:
- [ ] 1: Create Team html page (Elijah)
- [ ] 2: Create accessibility settings for different types of user (non-member employee, member employee, manager) (Elijah)
- [ ] 3: Create view to return relevant information to display (Elijah)
- [ ] 4: Add team data into database for examples (at least 5) (Ola & Jacob)

**Comment by sjiang1** [comment]
Please add an acceptance criterion for unauthorized access:
If an unauthorized profile accesses a Team page or if a private team page is accessed by non-team members:
....
Please also do this for Project View and Person View

**Comment by jelwell4** [comment]
Updated Acceptance Criteria:

If an unauthorized user accesses a Team page or if a private team page is accessed by non-team members:

redirect to log in or home page if already logged in
