### ISSUE TITLE
Feat: Creation of user page to display a given user

### ISSUE THREAD

**Issue by ESmit147** [COSC481W-2022Winter/capstone-wicrosoft#27]
As a user, I would like to view other users profile. The ability to see basic information like the teams, projects, and skills that the user has or is attached to.

Constraints:
1. Person must be within the database
2. Have page that shows specific person
3. url takes person_id parameter and displays person info

Acceptance Criteria:
If an authorized profile accesses a Persons page:
- should be able to view basic information pertaining to that employee:
- Teams
- Projects
- Skills
- Personal

If an unauthorized user accesses a person page 
- redirect to log in screen

Tasks:

- [ ] 1: Create Person html page (Elijah)
- [ ] 2: Create view to gather data from database for a given user to display (Elijah)
- [ ] 3: Add person data into database (at least 20) (Ola & Jacob)

**Comment by jelwell4** [comment]
Updated Acceptance Criteria:

If an unauthorized user accesses a person page 
- redirect to log in screen
