### ISSUE TITLE
Feat: Creation of Project Page to Display a given project

### ISSUE THREAD

**Issue by ESmit147** [COSC481W-2022Winter/capstone-wicrosoft#28]
As a user, I would like to view a project and the details revolving around that project. See the description, owner, and the teams attached to said project.

Constraints:
1. Project must be within the database
2. Have page that shows specific project
3. url takes project_id parameter and displays project info
4. Project must be of type "public" to be viewed by non-managers.

Acceptance Criteria:
If an authorized profile accesses a Project page:
- should be able to view basic information pertaining to that Project:
- Owner
- Description
- Teams

If an unauthorized user accesses a Project page or if a private project page is accessed by non-team members:
- redirect to log in or home page if already logged in

Tasks:

- [ ] 1: Create Project html page (Elijah)
- [ ] 2: Add Project Data into the Database for examples (at least 5) (Ola & Jacob)
- [ ] 3: Create view to return relevant data to display on page (Elijah)

**Comment by jelwell4** [comment]
Updated Acceptance Criteria:

If an unauthorized user accesses a Project page or if a private project page is accessed by non-team members:
- redirect to log in or home page if already logged in
