### ISSUE TITLE
Create Accounts for New Employees

### ISSUE THREAD

**Issue by KellyLieske** [COSC481W-2022Winter/capstone-wicrosoft#3]
As a manager, I would like to easily create accounts for new employees that join the company. Would like the ability to upload an excel file or csv to a page, which will automate the creation of multiple employees.

Acceptance Criteria:
If user is manager show the link to add new employees.

If user uploads file makes sure it is excel or csv file type

If file is not properly organized, return error with specific indexes of the malformed records and don't add anything database

If file is properly organized, return list of employees created and allow the manager to save that output. 

Tasks:
1. Database must be created (Jacob & Brian)
2. pyexcel plugin must be included into project (Brian)
2.1 Testing pyexcel with excel form processing
3. use pyexcel to take formatted excel file and load data into database (Jacob)

**Comment by bsimmo11** [comment]
Manually closing issue, because "closes issueNumber" is not working.
