### ISSUE TITLE
Feat: Create Search Utility

### ISSUE THREAD

**Issue by jelwell4** [COSC481W-2022Winter/capstone-wicrosoft#30]
As a user, I would like to search through the companies teams, projects, and users. Gives me the ability to research teams and projects

Constraints:
1. Individual page with Search input
2. Needs filtering ability to choose teams, projects, or persons

Acceptance Criteria:
Page must have a input textbox that allows the users to type in some text. 

The search box must have three optional filters: Teams, Projects, Persons.

Once the user types text into the search box, the entities will be returned in a card view in the remainder of the html page, with small details about the entity and link to the page type (i.e. specific team page, specific person page, specific project page)

Tasks:
1. Create basic html page with input textbox. (Brian)
1.1 Have a flexbox container in the content area of the screen to hold search. (Brian)
2. Make view that return the basic html page. (Brian)
3. Make view that takes in search query and returns the search entities. (Brian)

**Comment by sjiang1** [comment]
Task 3 "Have database filled with meaningful data within the User, Projects, Teams. (Ola & Jacob)" is duplicated with the tasks in other issues. Please confirm this is the case.

**Comment by bsimmo11** [comment]
We have taken the Ola and Jacob off of this issue/task since they will do the same stuff within other PBI's. So this issue will not have the "add useful data to database" task.
