### ISSUE TITLE
Design Team Creation Form

### ISSUE THREAD

**Issue by KellyLieske** [COSC481W-2022Winter/capstone-wicrosoft#4]
As a team manager, I would like to be able to use a form to create a team with a specific purpose and add as many team members I see fit.

Acceptance Criteria:
1. User must be manager
2. Have validation to make sure Team data is properly input.
3. Upon submission, if success inform user Team was created.
3.1. If fail, inform user.

Tasks:
Front-End (Faizan A., Ola I.)
1. Create base form with no styling that matches the correct input aligned with the database Team table columns.
2. Style form once base is created

Back-End (Kelly L.)
1. Django views that take base form input for team creation
2. Validate that Team record was properly created.

**Comment by sjiang1** [comment]
Acceptance criteria:

1. User must be manager. *If not, the user cannot access the form using the URL.*
2. Have validation to make sure Team data is properly input. *If not, a warning will display to describe what input is not proper.*
3. Upon submission, if success informs the user Team was created.
   3.1. If fail, inform user Team not successfully created.
