### ISSUE TITLE
Design Team Creation Form

### ISSUE THREAD

**Issue by bsimmo11** [COSC481W-2022Winter/capstone-wicrosoft#5]
Acceptance Criteria:
1. User must be manager
2. Have validation to make sure Team data is properly input. 
3. Upon submission, if success inform user Team was created. 
3.1. If fail, inform user. 

Tasks:
Front-End (Faizan A., Ola I.)
1. Create base form with no styling that matches the correct input aligned with the database Team table columns.
2. Style form once base is created

Back-End (Kelly L.)
1. Django views that take base form input for team creation
2. Validate that Team record was properly created.

**Comment by ESmit147** [comment]
Duplicate
