### ISSUE TITLE
Remove Announcements Section

### ISSUE THREAD

**Issue by bsimmo11** [COSC481W-2022Winter/capstone-wicrosoft#50]
Acceptance Criteria:
- Remove announcements portion of profile/home page
- Remaining page content should be balanced and presentable

Tasks:
1. Edit profile.html to remove the announcements flexbox (Jacob)
2. Update remaining fields to look presentable on profile/home page (Jacob)

**Comment by sjiang1** [comment]
I assume @jelwell4 will be the assignee for all the tasks.

**Comment by jelwell4** [comment]
Updated, sorry for missing this @sjiang1 . Thanks!
